### ISSUE TITLE
Update chart-testing tool

### ISSUE THREAD

**Issue by PennyScissors** [rancher/helm3-charts#13]
The chart-testing tool needs to be updated. 
There has been significant changes since it was last updated.
For that reason it would be best to fork it from the official helm repo [here](https://github.com/helm/chart-testing) and modify it according to the commits by guangbo [here](https://github.com/guangbochen/chart-testing/commits/master) to add support for multi-level folder parsing as needed for our catalog's directory structure.

**Comment by datamattsson** [comment]
Will this resolve #25 ?

**Comment by PennyScissors** [comment]
Close due to filing issue as a tech debt task.
